image: python:3.12-slim

variables:
  BINARY_NAME: "claia"
  ARTIFACT_PATH: "dist"
  WHL_DIR: "whl"
  B2_PATH: "" # path inside the bucket to upload to, leave empty for root bucket path
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  PYTHONPATH: "$CI_PROJECT_DIR"

stages:
  - test
  - build_and_upload
  - publish


########################################################################
#                            COMMON ANCHORS                            #
########################################################################
.setup_dependencies:
  before_script:
    - apt-get update && apt-get install -y build-essential curl jq zip git


# Authenticate with Backblaze B2
.b2_auth: &b2_auth
  - >
    export B2_AUTH_TOKEN=$(curl -s -u "${B2_APPLICATION_KEY_ID}:${B2_APPLICATION_KEY}" \
      https://api.backblazeb2.com/b2api/v2/b2_authorize_account | jq -r .authorizationToken)
  - >
    export B2_API_URL=$(curl -s -u "${B2_APPLICATION_KEY_ID}:${B2_APPLICATION_KEY}" \
      https://api.backblazeb2.com/b2api/v2/b2_authorize_account | jq -r .apiUrl)


# Get upload URL and auth token
.b2_get_upload_url: &b2_get_upload_url
  - >
    export UPLOAD_AUTH=$(curl -s -H "Authorization: ${B2_AUTH_TOKEN}" \
      ${B2_API_URL}/b2api/v2/b2_get_upload_url \
      -d "{\"bucketId\":\"${B2_BUCKET}\"}")
  - export UPLOAD_URL=$(echo $UPLOAD_AUTH | jq -r .uploadUrl)
  - export UPLOAD_AUTH_TOKEN=$(echo $UPLOAD_AUTH | jq -r .authorizationToken)


# Upload artifacts to Backblaze B2 object storage
.b2_upload_files: &b2_upload_files
  - >
    if [ -z "$(find "${ARTIFACT_PATH}" -type f -print -quit)" ]; then
      echo "No files found in ${ARTIFACT_PATH}"; exit 1; fi
    find "${ARTIFACT_PATH}" -type f -print0 | while IFS= read -r -d '' file; do
      rel_path=${file#${ARTIFACT_PATH}/}
      case "$file" in
        *.txt) content_type="text/plain" ;;
        *.zip) content_type="application/zip" ;;
        *.whl) content_type="application/zip" ;;
        *)     content_type="application/octet-stream" ;;
      esac
      sha1=$(sha1sum "$file" | awk '{print $1}')
      curl -s -T "$file" -X POST \
        -H "Authorization: ${UPLOAD_AUTH_TOKEN}" \
        -H "X-Bz-File-Name: ${B2_PATH}${rel_path}" \
        -H "Content-Type: ${content_type}" \
        -H "X-Bz-Content-Sha1: $sha1" \
        ${UPLOAD_URL}
    done


.common_job_config: &common_job_config
  extends:
    - .setup_dependencies
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .pip-cache/


########################################################################
#                                 ALL                                  #
########################################################################
test:
  <<: *common_job_config
  stage: test
  script:
    - pip install -r build/requirements.txt
    - pytest
  artifacts:
    when: always
    reports:
      junit: report.xml
    expire_in: 1 week
  coverage: '/(?i)total.*? (100(?:\.0+)?|[1-9]?\d(?:\.\d+)?)%/'


########################################################################
#                                 MAIN                                 #
########################################################################
main_build_and_upload:
  <<: *common_job_config
  stage: build_and_upload
  script:
    # Build binary
    - chmod +x ./build/deploy.sh
    - ./build/deploy.sh --build-ubuntu-bin
    - ./build/deploy.sh --build-whl

    # Set bucket and credentials for main branch
    - export B2_BUCKET=${MAIN_B2_BUCKET_ID}
    - export B2_APPLICATION_KEY_ID=${MAIN_B2_APPLICATION_KEY_ID}
    - export B2_APPLICATION_KEY=${MAIN_B2_APPLICATION_KEY}

    # B2 Authentication and Upload
    - *b2_auth
    - *b2_get_upload_url
    - *b2_upload_files
  only:
    - main


publish_pypi:
  <<: *common_job_config
  stage: publish
  script:
    - python -m pip install --upgrade pip
    - pip install build twine
    - python -m build
    - python -m twine check dist/*
    - TWINE_USERNAME=gitlab-ci-token TWINE_PASSWORD=${CI_JOB_TOKEN} python -m twine upload dist/* --skip-existing
  only:
    - main


########################################################################
#                                 DEV                                  #
########################################################################
dev_build_and_upload:
  <<: *common_job_config
  stage: build_and_upload
  script:
    # Build source package
    - chmod +x ./build/deploy.sh
    - ./build/deploy.sh --build-whl
    - ./build/deploy.sh --export

    # Set bucket and credentials for dev branch
    - export B2_BUCKET=${DEV_B2_BUCKET_ID}
    - export B2_APPLICATION_KEY_ID=${DEV_B2_APPLICATION_KEY_ID}
    - export B2_APPLICATION_KEY=${DEV_B2_APPLICATION_KEY}

    # B2 Authentication and Upload
    - *b2_auth
    - *b2_get_upload_url
    - *b2_upload_files
  only:
    - dev


publish_testpypi:
  <<: *common_job_config
  stage: publish
  script:
    - python -m pip install --upgrade pip
    - pip install build twine
    - python -m build
    - python -m twine check dist/*
    - TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/ TWINE_USERNAME=gitlab-ci-token TWINE_PASSWORD=${CI_JOB_TOKEN} python -m twine upload dist/* --verbose
  only:
    - dev
