volumes:
  ollama:
  models:

services:
  dev:
    image: clai:dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # volumes:
    #   - ./:/app
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           device_ids: ['0']
    #           capabilities: [gpu]
