services:
  claia:
    stdin_open: true
    tty: true
    image: claia
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.test
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client /app/src-old/__main__.py
    volumes:
      - ../src-old:/app/src-old
      - ../modules:/app/modules
      - ../storage:/app/storage
      - ../.claia_history:/app/.claia_history
      - C:\.cache\claia\models:/app/models
    ports:
      - 5678:5678
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
