volumes:
  # ollama:
  models:
  files-db:
  files-config:
  files:

services:
  claia:
    image: clai:dev
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../.env
    volumes:
      - files:/app/files
      # - ./output:/app/files
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  claia-test:
    image: clai:test
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.test
    env_file:
      - ../.env
    volumes:
      - files:/app/files
      # - ../src-old:/app/src-old
      # - ../modules:/app/modules
    # - ./output:/app/files
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  claia-run-tests:
    image: clai:run-tests
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.run-tests
    env_file:
      - ../.env
    volumes:
      - files:/app/files
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  claia-package:
    image: clai:package
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.package
    env_file:
      - ../.env
    volumes:
      - files:/app/files
    # - ./output:/app/files
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  files:
    image: filebrowser/filebrowser:s6
    ports:
      - ${IP:-0.0.0.0}:${FILES_PORT:-8080}:80
    # environment:
    #   - PUID=$(id -u)
    #   - PGID=$(id -g)
    volumes:
      - files-db:/database # filebrowser.db
      - files-config:/config # settings.json
      - files:/srv
