FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
  zip \
  nano \
  curl

# RUN apt-get update && apt-get install -y \
#   pulseaudio \
#   libportaudio2 \
#   alsa-utils \
#   sox \
#   libsox-fmt-all \
#   espeak-ng \
#   cmake \
#   nano \
#   sshpass

# COPY requirements.txt .
# RUN pip install -r requirements.txt --no-cache-dir

COPY src/ src/
COPY package.sh .
COPY requirements.txt .
COPY README.md .

RUN chmod +x package.sh
RUN ./package.sh

# ENTRYPOINT [ "python", "main.py" ]