# NOTE: No print statement should ever output more than 72 characters per console line

def unrecognizedCommand() -> None:
  print("Command incomplete or not recognized")

def allCommands() -> None:
  print("Here is a list of available commands:")
  print("  system, sys, s")
  print("    - technical commands such as exiting the program and clearing the screen")
  print("  character, characters")
  print("    - commands related to characters or system promts")
  print("  conversation, conversations")
  print("    - commands related to conversations and saved messages")
  print("  model, models")
  print("    - commands related to selecting and managing language models")
  print("  zammad, z")
  print("    - commands related to interacting with Zammad support ticket system")
  print("  massedcompute, mc")
  print("    - commands related to deploying and managing GPU instances")

def characterCommands() -> None:
  print("Here are the available character commands:")
  print("  list <optional: character>")
  print("    - list all available characters or details about a specific character")
  print("  remove, unset <character>")
  print("    - remove the current character selection")
  print("  set, select <character>")
  print("    - select a character to use in the conversation")
  print("  print, current")
  print("    - display the current character selection")

def conversationCommands() -> None:
  print("Here are the available conversation commands:")
  print("  list")
  print("    - list any saved conversations")
  print("  new")
  print("    - start a new conversation")
  print("  print")
  print("    - display the current conversation")
  print("  load <filename>")
  print("    - load a saved conversation")

def experimentalCommands() -> None:
  print("Here are the available expirimental commands:")
  print("(it's a secret)")

def modelCommands() -> None:
  print("Here are the available model commands:")
  print("  list")
  print("    - list all available models")
  print("  list <model>")
  print("    - display details about a specific model")
  print("  set, select <model>")
  print("    - select a model to use for generation")
  print("  set, select <model> <source>")
  print("    - select a model with specific source to use for generation")
  print("  print, current")
  print("    - display the current model selection")
  print("  vllm zone")
  print("    - display the current VLLM zone")
  print("  vllm zone <zone>")
  print("    - set the VLLM zone")
  print("  vllm email")
  print("    - display the current VLLM email")
  print("  vllm email <email>")
  print("    - set the VLLM email")
  print("  vllm subdomain")
  print("    - display the current VLLM subdomain")
  print("  vllm subdomain <subdomain>")
  print("    - set the VLLM subdomain")

def vllmCommands() -> None:
  print("Here are the available VLLM commands:")
  print("  zone")
  print("    - display the current VLLM zone")
  print("  zone <zone>")
  print("    - set the VLLM zone (e.g., example.com)")
  print("  email")
  print("    - display the current VLLM email")
  print("  email <email>")
  print("    - set the VLLM email (used for SSL certificates)")
  print("  subdomain")
  print("    - display the current VLLM subdomain")
  print("  subdomain <subdomain>")
  print("    - set the VLLM subdomain (e.g., vllm)")

def systemCommands() -> None:
  print("Here are the available system commands:")
  print("  clear, cls, c")
  print("    - clear the screen")
  print("  quit, exit, q")
  print("    - terminate the clai software")
  print("  get log_level")
  print("    - display the current log level")
  print("  set log_level <level>")
  print("    - set the log level (debug, info, warning, error, critical)")

def zammadCommands() -> None:
  print("Here are the available Zammad commands:")
  print("  list, query")
  print("    - list tickets using the default query (open tickets)")
  print("  list, query <query_name>")
  print("    - list tickets using a specific query")
  print("  details <ticket_id>")
  print("    - display details for a specific ticket")
  print("  process")
  print("    - process untagged tickets with AI for summarization and tagging")

def massedcomputeCommands() -> None:
  print("Here are the available MassedCompute commands:")
  print("  deploy cheapest <image_id> <instance_name> <startup_script> <ssh_key1> ... <ssh_keyN>")
  print("    - Deploy cheapest available GPU instance")
  print("  deploy specific <image_id> <instance_name> <product_name> <startup_script> <ssh_key1> ... <ssh_keyN>")
  print("    - Deploy a specific GPU instance")
  print("  terminate <uuid|name> <uuid2|name2> ... <uuidN|nameN>")
  print("    - Terminate one or more instances by UUID or name")
  print("  details <uuid|name>")
  print("    - Get detailed information about a specific instance")
  print("  ssh <uuid|name>")
  print("    - Connect to instance via SSH using UUID or instance name")
  print("  run <uuid|name> <script_name>")
  print("    - Run a predefined script on an instance")
  print("  list")
  print("    - List running instances (default)")
  print("  list instances")
  print("    - List running instances")
  print("  list gpus [sort_by]")
  print("    - List available GPU configurations")
  print("    - Optional sort_by: price/p, vram/v, value/val, available/a")
  print("    - Add '-' prefix for reverse sort (e.g., -price)")
  print("  list images")
  print("    - List available VM images")